### ISSUE TITLE
Document how to create submodules/upstream repos in a subdirectory of the student's private repo

### ISSUE THREAD

**Issue by kevincoakley** [kevincoakley/DSE_Summer_2015#13]

**Comment by yoavfreund** [comment]
Seems like in the newer version of git the creation of the submodule also clones the contents (other than if there are submodules of that repository)

https://chrisjean.com/git-submodules-adding-using-removing-and-updating/

**Comment by kevincoakley** [comment]
Changes made to a Git repository that is added as a submodule are committed to the original repository, not the student's repository. 

See my example:

https://github.com/kevincoakley/submodule/blob/master/tests/01%20submodule%20test%20with%20mrjob.ipynb

**Comment by kevincoakley** [comment]
I created an example of how branches could be used with different remotes:

https://github.com/kevincoakley/submodule/blob/master/tests/02%20course%20repo%20on%20own%20branch.ipynb

**Comment by yoavfreund** [comment]
We will stay with a simpler solution. The notebooks and data will be kept in a repository for each course. The students will clone this repository and then move it's content into a directory in their own repository.
