### ISSUE TITLE
Create GitHub Accounts for students

### ISSUE THREAD

**Issue by kevincoakley** [kevincoakley/DSE_Summer_2015#15]
Create GitHub accounts for students (if possible) instead of having them create their own account and adding it to the organization.

**Comment by kevincoakley** [comment]
There is no API for creating user account, each account would have to be manually created by the DSE program and the password emails to the student.

**Comment by yoavfreund** [comment]
Use a name of the form mas-dse-<ucsd email id>

Kevin Can either ask them to do it or do it for them
